<div class="pr">
<h1>Nextcloud 12 Beta Introduces the Next Generation of Secure Collaboration</h1>
<p><strong>May 2 2017, Stuttgart, Germany.</strong> Nextcloud GmbH, the leading global supplier of open source enterprise sync and share communication technology, announces the beta of Nextcloud 12 extending the technological lead of their enterprise product. Nextcloud 12 Beta solidifies the strong, stable base for sharing and syncing, adding groundbreaking new capabilities in the area of collaboration and communication like push notifications, screen sharing for video chats and improved sharing flexibility.</p>

<blockquote>Among IT departments looking for tight control over their data, Nextcloud 11 earned a reputation of a rock solid release moving the goal posts on security and scalability</blockquote> said Frank Karlitschek, managing director at Nextcloud. <blockquote>We have invited the community to help test Nextcloud 12 Beta, report bugs and help us once again deliver the most reliable solution for syncing, sharing and collaboration in the enterprise!</blockquote>

<p>Nextcloud 12 Beta integrates much requested collaboration capabilities on top of its core of secure enterprise file sync and share. Sharing capabilities have been extended, enabling users to share public links to customers or clients with individual permissions, passwords and expiration dates by email. Comments on files can be addressed directly in an audio/video call, featuring screen sharing and enabling simultaneous, collaborative editing with the optional Collabora Online integration even over public links with users who have no account on the server. Users now have the ability manage their own contacts in groups using the Circles app and will be notified of new shares or incoming calls by push notifications on the mobile and desktop clients, new versions of which will be released in the coming weeks.</p>

<p>Administrators benefit from major new features increasing their control over events on the server. The Excludedirs app  app enables a specific folder pattern to be excluded from being indexed and made visible in Nextcloud, useful to, for example exclude snapshot subfolders as used on enterprise storage systems. The Quota-warning app can tell users when they are reaching the limits of their storage while the downloadActivty app allows users and admins to be notified when shared files are downloaded. The jsloader app can enable integration of arbitrary javascript, enabling admins to use monitoring tools like Piwik or Google Analytics to track usage of their server. The Guest app enables creating guest users and the Impersonate app lets a admin take temporary control over a user account. Other improvements include the 'endorse password' feature, API and bug reporting enhancements and more.</p>

<blockquote>Secure collaboration is a vital requirement for modern enterprises and we're delighted to be a key partner for Nextcloud in providing the most powerful collaboration and communication solution to customers,</blockquote> said Michael Meeks, General Manager of Collabora Productivity <blockquote>Collabora 2.1 is coming soon and will deliver significant new capabilities like comments and tracking changes, bringing efficient collaboration to the next level.</blockquote>

<p>Nextcloud 12 Beta builds on the scalability and reliability improvements introduced with Nextcloud 11, bringing a combined doubling of performance and far improved scalability over their predecessors and increasing security with new, innovative hardenings and protections. Authentication has received an overhaul, enabling the clients to support a virtually unlimited range of authentication mechanisms including two-factor authentication, OAUTH, SAML and more. Protected by improved Brute Force Protection and the new Rate Limiting, Nextcloud 12 servers put up strong barriers to abuse. The upgrade process has been made more reliable and apps will no longer be disabled on bugfix updates, decreasing the maintenance load for server administrators. The appstore, with over 40 apps already available for Nextcloud 12 Beta, was also extended featuring internationalization, app ownership migration and more.</p>

<p><strong>About Nextcloud</strong></br />
Nextcloud offers a unique-in-the-industry fully open source solution for on-premise data handling and communication with an uncompromising focus on security and privacy. Nextcloud brings together universal access to data with next-generation secure communication and collaboration capabilities under direct control of IT and integrated with existing compliant infrastructure. Nextcloud's open, modular architecture, emphasis on security and advanced federation capabilities enable modern enterprises to leverage their existing assets within and across the borders of their organization. For more information, visit <a href="https://nextcloud.com">https://nextcloud.com</a> or follow <a href="https://twitter.com/nextclouders">@Nextclouders on Twitter.</a></p>

<p><strong>Links:</strong><br />
Release blog with full feature overview, screenshots and videos: <a href="https://nextcloud.com/blog/nextcloud-12-beta-introduces-the-next-generation-of-secure-collaboration/">Nextcloud 12 Beta Introduces the Next Generation of Secure Collaboration</a><br />
Blog by Nextcloud founder Frank Karlitschek on opensource.com on the vision behind Nextcloud 12: <a href="https://opensource.com/article/17/5/next-big-challenge-open-source-rich-collaboration-software">The next big challenge for open source: rich collaboration software</a><br />
Blog covering the new collaboration and communication features: <a href="https://nextcloud.com/blog/nextcloud-12-redefining-file-sync-and-share-with-collaboration-and-communication/">Nextcloud 12: Redefining File Sync and Share with Collaboration and Communication</a><br />
Blog covering the Bruteforce Protection and Rate Limiting: <a href="https://nextcloud.com/blog/security-in-nextcloud-12-bruteforce-protection-and-rate-limiting-for-developers/">Security in Nextcloud 12: Bruteforce Protection and Rate Limiting for developers</a><br />
Blog covering the new authentication mechanisms: <a href="https://nextcloud.com/blog/security-in-nextcloud-12-new-authentication-mechanisms/">Security in Nextcloud 12: new authentication mechanisms</a><br />
Videos introducing the new features in Nextcloud 12: <a href="https://www.youtube.com/playlist?list=PL4eBKdNy6FCEzwAnIvWoimKsA9ltdD0f0">Nextcloud 12 on YouTube</a><br />
About Nextcloud: <a href="https://nextcloud.com/about">nextcloud.com/about</a><br />
<br />
</p>
<p><strong>Press contacts</strong><br />
Nextcloud GmbH<br />
Jos Poortvliet<br />
Kronenstraße 22A<br />
D-70173 Stuttgart, Germany<br />
e-mail: <a href="mailto:pr@nextcloud.com">pr@nextcloud.com</a></p>
</div>
