<div class="pr"><h1>Nextcloud delivers secure enterprise functionality backed by expert support and with partner-provided iOS client</h1>

<p><strong>Stuttgart, Germany - June 5th, 2016</strong> Nextcloud, the next generation privacy-aware open source file sync and share, communication and collaboration solution announces immediate availability of Enterprise Support Subscriptions for the latest Nextcloud 9 update. This release introduces security fixes courtesy of the Nextcloud Security Bug Bounty Program and crucial enterprise functionality under an open source license for businesses seeking to regain control over their data and communication. The release is accompanied by the introduction of a state-of-the-art iOS client through the partnership with TWSweb, makers of the popular Cryptocloud iOS app.</p>

<p>Introducing Windows Network Drive storage support, Shibboleth/SAML authentication integration, theming capabilities and control over password policy, the latest Nextcloud 9 update delivers enterprise grade stability and security with the capabilities organizations need to manage and secure their data and communication. Rather than employing a limited open core model, the development of these features was done in public under an open source license with input from a variety of third parties including members seeking to deploy Nextcloud in educational and large corporate environments, in part through the GÉANT-backed Open Cloud Mesh initiative Nextcloud joined yesterday.</p>

<p>For this release Nextcloud announces immediate availability of a range of Enterprise Support Subscriptions delivering organizations access to the technical expertise and support they need to be successful and secure. By providing pro-active support Nextcloud enables customers deploy a reliable solution for universal file access and communication while helping them identify and address opp vulnerabilities and harden their servers to protect the integrity and safety of mission-critical data.</p>

<p>"Nextcloud employs an open approach to support giving direct access to  Nextcloud engineers, the latest knowledge and best practices", said Frank Karlitschek. "And we do this offering reasonable pricing in multiple tiers capable of fitting different business needs, from small businesses with our Spreedbox to large enterprises with a subscription"</p>

<p>Besides enterprise functionality and support, Nextcloud partners with TWSweb, creators of the well known Cryptocloud iOS app, to deliver a capable and proven iOS client to customers and users, available in the Apple Appstore right away.</p>

<p>"We're excited to partner up with Nextcloud to deliver a premier file handling experience on iOS", said Marino Faggiana, CEO and founder at T.W.S. "Built on a proven code base, the Nextcloud client brings an easy user interface and reliable syncing to users and we look forward to innovating together on further capabilities with the Nextcloud team"</p>

<p>Nextcloud 9 is available immediately and contains security-critical updates courtesy of our highly-acclaimed Security Bug Bounty program paying a open-source record up to USD 10000 to security experts who disclose security issues to us. Users are strongly urged to upgrade at their earliest convenience. Enterprises and organizations looking for quick deployments and reliable functioning backed by a qualified enterprise support team can find our Enterprise Support Subscription options on our website under http://nextcloud.com/enterprise</p>

About Nextcloud
N<p>extcloud offers a unique-in-the-industry fully open source solution for on-premises data handling and communication with a uncompromising focus on security and privacy. Nextcloud brings together universal access to data with next-generation secure communication and collaboration capabilities under direct control of IT and integrated with existing compliant infrastructure. Nextcloud's open, modular architecture, emphasis on security and advanced federation capabilities enable modern enterprises to leverage their existing assets within and across the borders of their organization. For more information, visit https://nextcloud.com</p>

<p>Find the announcement of Nextcloud joining the Open Cloud Mesh initiative here: https://nextcloud.com/nextcloud-joins-open-cloud-mesh/</p>
 </div>
