<head>
    <link href="<?php echo get_template_directory_uri(); ?>/assets/css/pages/pressrelease.css" rel="stylesheet">
<meta itemprop="image" content="https://nextcloud.com/media/dashboard-integrations.png">
<meta name="twitter:image" content="https://nextcloud.com/media/dashboard-integrations.png">
<meta name="twitter:image:src" content="https://nextcloud.com/media/dashboard-integrations.png">
<meta property="og:image" content="https://nextcloud.com/media/dashboard-integrations.png">
</head>
<div class="background generic-background">
	<div class="container">
		<div class="row">
			<div class="col-md-6 topheader">
                <h1>Press release</h1>
            </div>
        </div>
    </div>
</div>

<section class="section--pressrelease">
<div class="container">
<div class="row">
<div class="pr">
<h1>Nextcloud becomes an integration platform with Microsoft, Google, Slack, Moodle, Github, HPI School-Cloud, Jira, Dropbox, Matrix and more</h1>
<p><em>Focus on integrating thrid party platforms announced at Nextcloud Conference</em></p>
<p><em>October 3, 2020, Berlin</em> - Nextcloud GmbH, provider of the most deployed on-premises content collaboration platform announces a shift towards deeper integration with third party platforms and the results of the first efforts in this direction. Integrations in Nextcloud 20 include dominant solutions like Slack, MS Online Office Server, SharePoint and Teams, Jira and Github as well as open source contenders like Matrix, Gitlab, Zammad and Moodle among many others.</p>
<blockquote>
<p>Nextcloud has become the central communication and document exchange hub for many organizations. Integration with third party solutions deployed at our customers or their partners, suppliers and customers will further improve their productivity and facilitate collaboration within and across organizational boundaries.</p>
</blockquote>
<p>-- Frank Karlitschek, CEO and founder of Nextcloud GmbH</p>
<p>Since its inception Nextcloud differentiated itself as a solution capable of unlocking the many storage silos in modern organizations, bringing data from SharePoint, FTP, Windows Network Drive, Object Storage and other solutions in a single interface without forcing costly data migration. Integrating in existing security and authentication infrastructure, Nextcloud successfully sped up deployment and improved productivity at thousands of businesses.</p>
<p>With a growing array of often SaaS based solutions, the kind and number of data storages has exploded, adding chat channels, planning tools, and more into a dizzying compliance and data loss risk factor for system administrators. The global health crisis has compounded this problem, with improved adoption of online communication tools splintering collaboration in and between organizations further. With Nextcloud 20 a wide range of new integration features debuts, connecting Nextcloud to many different platforms from third party vendors. This creates a more integrated experience for users, allowing them to react faster to new tasks, avoid context switching and plan their time more effectively.</p>
<p>Nextcloud Hub 20 builds on an open API, the Open Collaboration Services, making integration efforts transparent and well documented. The release introduces over 3 dozen integrations with a wide range of solutions. * Bridges are introduced between the Nextcloud Talk chat service with Microsoft Teams, Slack, Matrix, IRC, XMPP, Steam and many more. * Nextcloud’s integrated, unified search can provide results from ticketing systems like Jira and Zammad, development platforms like Github and Gitlab, e-learning systems like Moodle and HPI, forums like Discourse and Reddit, social media like Twitter and Mastodon and more. * Nextcloud Talk can call external applications through commands and a new Webhooks Flow integration enables third party platform activities to trigger or be triggered by the Nextcloud workflow capabilities.</p>
<blockquote>
<p>Imagine a invoice generated by the accounting system triggering a conversion of a word document to a PDF file in Nextcloud through Webhooks Flow and, in turn, creating a chat message with public link to the PDF via a Talk bridge into a Slack channel of the customer. The account manager can receive a push notification on their mobile device when the invoice payment comes in, or see it the next morning when they log into Nextcloud on their Dashboard and respond with a Talk command to mark the invoice paid in the accounting system. The opportunities to optimize workflows at our customers are endless.</p>
</blockquote>
<p>-- Andreas Rode, head of sales at Nextcloud GmbH</p>
<p>Together with its partners, Nextcloud has released a series of press releases covering some of the integrations developed, including Moodle, HPI, Gitlab, Hancom Office and Zammad.</p>
<h2>About Nextcloud</h2>
<p>Nextcloud Hub is the industry-leading, fully open source, on-premises team productivity platform, combining the easy user interface of consumer-grade cloud solutions with the security and compliance measures enterprises need. Nextcloud Hub brings together universal access to data through mobile, desktop and web interfaces with next-generation, on-premise secure communication and collaboration features like real-time document editing, chat and video calls, putting them under direct control of IT and integrated with existing infrastructure.</p>
<p>Nextcloud’s easy and quick deployment, open, modular architecture and emphasis on security and advanced federation capabilities enable modern enterprises to leverage their existing file storage assets within and across the borders of their organization. For more information, visit <a href="https://nextcloud.com">nextcloud.com</a> or follow <span class="citation" data-cites="Nextclouders">[@Nextclouders]</span>(https://twitter.com/Nextclouders) on Twitter.</p>
<h2>Links</h2>
<ul>
<li><a href="https://nextcloud.com/about">About Nextcloud</a></li>
<li><a href="https://nextcloud.com/conf-2020">Nextcloud Conference 2020</a></li>
<li><a href="https://nextcloud.com/blog/TBD">Blog post about integrations in Nextcloud 20</a></li>
<li><a href="https://apps.nextcloud.com/categories/integration">Overview of integrations in Nextcloud app store</a></li>
<li><a href="https://open-collaboration-services.org">Open Collaboration Services website</a></li>
<li><a href="https://nextcloud.com/press/TBD">Gitlab integration press release</a></li>
<li><a href="https://nextcloud.com/press/TBD">Hancom Office integration press release</a></li>
<li><a href="https://nextcloud.com/press/TBD">HPI integration press release</a></li>
<li><a href="https://nextcloud.com/press/TBD">Moodle integration press release</a></li>
<li><a href="https://nextcloud.com/press/TBD">Zammad integration press release</a></li>
<li><a href="https://nextcloud.com/press/TBD">Nextcloud 20 announcement press release</a></li>
<li><a href="https://nextcloud.com/press/TBD">This press release</a></li>
</ul>
<h2>Graphics</h2>
<ul>
<li><a href="https://cloud.nextcloud.com/s/z5p7HsND8wwcSye/preview">Screenshot of search in Nextcloud Hub 20</a></li>
<li><a href="https://cloud.nextcloud.com/s/wrGcbJQaaByMWSG/preview">Screenshot of Dashboard widgets in Nextcloud Hub 20</a></li>
<li><a href="https://cloud.nextcloud.com/s/YWXZMo2AoLsN7WD/preview">Screenshot of Talk bridging Slack and IRC in a room</a></li>
</ul>
<h2>Press contacts</h2>
<p>Nextcloud GmbH<br />
Jos Poortvliet<br />
Phone: +49 (0) 171 121 7528<br />
jos.poortvliet<a href="mailto:pr@nextcloud.com">@nextcloud.com</a></p>
</div>
</div>
</div>
</section>

